import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.scss";
import { Pstyle } from "../styled/base"; // pstyle不行
import { Button } from "antd-mobile";
import styled from "styled-components";
const Buttons: any = styled(Button)`
  width: 100px;
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next Appds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Pstyle fontsize="22px" height="50px">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Pstyle>
        <Buttons type="primary">Start</Buttons>
      </main>
    </div>
  );
}
